/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/ft_memset.check" instead.
 */

#include <check.h>

#line 1 "tests/ft_memset.check"
#include "libft.h"
#include "string.h"

START_TEST(ft_memset_test)
{
#line 5
	char buf_expected[10000];
	char buf_actual[10000];

	ck_assert_mem_eq(ft_memset(buf_actual, 5, 10000), memset(buf_expected, 5, 10000), 9999);
	ck_assert_mem_eq(buf_expected, buf_actual, 9999);

	ck_assert_mem_eq(ft_memset(buf_actual, 'A', 10000),	memset(buf_expected, 'A', 10000), 10000);
	ck_assert_mem_eq(buf_expected, buf_actual, 10000);

	ck_assert_mem_eq(
		ft_memset(buf_actual, 12345, 10000),
		memset(buf_expected, 12345, 10000),
		10000
	);
	ck_assert_mem_eq(buf_expected, buf_actual, 10000);

	//ck_assert_int_eq(5, 6);
#include <check.h>
#include "libft.h"

#ifndef INT_MAX
# define INT_MAX		INT32_MAX
#endif

#ifndef INT_MIN
# define INT_MIN		INT32_MIN
#endif


}
END_TEST

START_TEST(ft_min_test)
{
#line 14
	fail_unless(ft_min(INT_MAX, 2) == 2, "INT_MAX vs 2 failed");
	fail_unless(ft_min(INT_MAX, INT_MAX) == INT_MAX, "INT_MAX vs INT_MAX failed");
    fail_unless(ft_min(INT_MIN, INT_MAX) == INT_MIN, "INT_MIN vs INT_MAX failed");
    fail_unless(ft_min(-3, 2) == -3, "-3 vs 2 failed");
    fail_unless(ft_min(0, -2) == -2, "0 vs -2 failed");
    fail_unless(ft_min(-3, -2) == -3, "-3 vs -2 failed");
#include <limits.h>
#include "libft.h"

#ifndef INT_MAX
# define INT_MAX		INT32_MAX
#endif

#ifndef INT_MIN
# define INT_MIN		INT32_MIN
#endif

}
END_TEST

START_TEST(ft_max_test)
{
#line 13
	fail_unless(ft_max(INT_MAX, 2) == INT_MAX, "INT_MAX vs 2 failed");
	fail_unless(ft_max(INT_MAX, INT_MAX) == INT_MAX, "INT_MAX vs INT_MAX failed");
    fail_unless(ft_max(INT_MIN, INT_MAX) == INT_MAX, "INT_MIN vs INT_MAX failed");
    fail_unless(ft_max(-3, 2) == 2, "-3 vs 2 failed");
    fail_unless(ft_max(0, -2) == 0, "0 vs -2 failed");
    fail_unless(ft_max(-3, -2) == -2, "-3 vs -2 failed");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, ft_memset_test);
    tcase_add_test(tc1_1, ft_min_test);
    tcase_add_test(tc1_1, ft_max_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
